name: release
on:
  release:
    types: [published]
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Publish package distributions to PyPI
        uses: le0nchw/pypi-poetry-publish@main
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          POETRY_DEPENDENCY_REGISTRY_NAME: "poe-shell"
          BRANCH: "main"
          PYTHON_VERSION: "3.11"
          POETRY_VERSION: "1.5.1"
          POETRY_CORE_VERSION: "1.6.1"
